S = program

program = expr-stmt+
expr-stmt = exp <";">
exp = exp0

<exp0> = exp1 | eq | ne | lt | le | gt | ge
eq = exp1 <"=="> exp1
ne = exp1 <"!="> exp1
lt = exp1 <"<"> exp1
le = exp1 <"<="> exp1
gt = exp1 <">"> exp1
ge = exp1 <">="> exp1

<exp1> = exp2 | add | sub
add = exp1 <"+"> exp2
sub = exp1 <"-"> exp2

<exp2> = exp3 | mul | div
mul = exp2 <"*"> exp3
div = exp2 <"/"> exp3

<exp3> = exp-atom | positive | negative
<positive> = <"+"> exp3
negative = <"-"> exp3

<exp-atom> = INT | <"("> exp1 <")">

INT = #"[0-9]+"
